### PR TITLE
adjust query for multiple search terms

### PR DESCRIPTION
**Pull request by jamesduncan**
Found one small adjustment...according to Brightcove at [http://docs.brightcove.com/en/video-cloud/media/guides/search_videos-guide.html#multipleTerms](url)

> One of the most commonly misunderstood aspects of search_videos is how you search on multiple terms. Say, for instance, that you want to return videos that have all of the following tags: bird; air; nature. To do this, you must include a separate all parameter for each search term, like this:

```
//api.brightcove.com/services/library?command=search_videos
&all=tag:bird&all=tag:air&all=tag:nature
&video_fields=id,name,shortDescription&get_item_count=true
&token=ZY4Ls9Hq6LCBgleGDTaFRDLWWBC8uoXQun0xEEXtlDUHBDPZBCOzbw..
```

This pull should identify when you are attempting to pass an array of search terms and adjust the query accordingly without affecting other query params that are passed as arrays and Brightcove wants them separated by commas in the request.

### CODE REVIEW

**Comment by jamesduncan** [comment]
Sorry as I look back through this I see that there is some syntax garbage that is being requested too...I am going to go back in and add back those tabs and the line at the end of the file so it only changes what is necessary.

**Comment by jamesduncan** [comment]
Okay...it took a few commits but I rebased and squashed them back into one. Sorry about the no newline at the end of the file.

**Comment by jamesduncan** [comment]
Oh...if there is a better place to store the multipleSearchTerms array let me know.

**Comment by nwbb** [comment]
Heya - sorry for the delay.  Yeah, let's throw the multipleSearchTerms at the top, just under all of the require's.   I can't think of a reason to expose it (then it would go in the constructor).

**Comment by jamesduncan** [comment]
Did I move it to the right spot?

**Comment by nwbb** [comment]
Yep, that'll work.

**Pull request merged**
