### PR TITLE
Video write APIs & proxy support

### PR DESCRIPTION
**Pull request by stevokk**
Inspired by @marcusthebrown

Took me longer than I'd have liked but there is a bug in the MediaApi that the file data cannot be in the form ahead of the video data. That's why the following pull request doesn't look the neatest when attaching form data.

Anyway, list of changes is as follows:
- create_video, update_video working
- http requests now using request library for easier form stream handling
- vows tests for create_video
- proxy support
- test video added
- Video facade object to match searching design
- fix package.json maintainer data type
- progress event callback when known payload size (can't be a stream)

We are implementing this library within our product next week so I will submit more changes/fixes if I find them.

Thanks for your original work, got us a good head start!

### CODE REVIEW

**Comment by nwbb** [comment]
Sorry it took a bit to review it all - nice work!.

**Comment by stevokk** [comment]
Great news, thanks! If I get time I will implement the "add_image" api call in a different pull request.

**Comment by stevokk** [comment]
@nwbb Can you publish the latest version to npm? I'm still getting the old one on "npm install"

**Comment by nwbb** [comment]
Yep, done.

**Pull request merged**
